"""added Comment and relationships with advert/user

Revision ID: 07e6f3a02b9d
Revises: b8e73525802f
Create Date: 2025-05-21 14:38:09.636292

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "07e6f3a02b9d"
down_revision: Union[str, None] = "b8e73525802f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("advert_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["advert_id"],
            ["advert.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comment")
    # ### end Alembic commands ###
