"""is_active

Revision ID: 6f4e2f535dd3
Revises: 9fdd899e7b7d
Create Date: 2025-05-19 21:01:52.174888

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f4e2f535dd3"
down_revision: Union[str, None] = "9fdd899e7b7d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "advert", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "advert", sa.Column("is_active", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("advert", "is_active")
    op.drop_column("advert", "created_at")
    # ### end Alembic commands ###
